import type { User, Trainset } from '@/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const userAvatar = PlaceHolderImages.find(img => img.id === 'user-avatar');

export const users: User[] = [
  {
    uid: 'admin01',
    name: 'Admin User',
    email: 'admin@metroflow.com',
    role: 'admin',
    avatarUrl: userAvatar?.imageUrl || '',
  },
  {
    uid: 'supervisor01',
    name: 'Supervisor User',
    email: 'supervisor@metroflow.com',
    role: 'supervisor',
    avatarUrl: userAvatar?.imageUrl || '',
  },
  {
    uid: 'viewer01',
    name: 'Viewer User',
    email: 'viewer@metroflow.com',
    role: 'viewer',
    avatarUrl: userAvatar?.imageUrl || '',
  },
];

export const trainsets: Trainset[] = [
  {
    id: 'TS01',
    fleetNumber: 'KM-01',
    status: 'service',
    mileage: 120500,
    certificates: [
      { dept: 'Braking', validFrom: '2023-01-01', validTo: '2025-01-01', status: 'valid' },
      { dept: 'HVAC', validFrom: '2023-06-15', validTo: '2024-06-15', status: 'expiring_soon' },
    ],
    jobCards: [{ id: 'JC-789', type: 'Wheel Inspection', severity: 'medium', status: 'open' }],
    branding: { contractId: 'BR-A1', exposureHoursRequired: 200, exposureAchieved: 150 },
    cleaningReady: true,
    bayPosition: 'A1',
    lastUpdated: new Date().toISOString(),
    rank: 1,
    score: 95,
    reasons: { fitnessScore: 0.8, brandingScore: 0.9, mileageBalancing: 0.7, otherFactors: ['High priority branding'] },
  },
  {
    id: 'TS02',
    fleetNumber: 'KM-02',
    status: 'service',
    mileage: 98000,
    certificates: [{ dept: 'Braking', validFrom: '2023-02-01', validTo: '2025-02-01', status: 'valid' }],
    jobCards: [],
    branding: null,
    cleaningReady: false,
    bayPosition: 'A2',
    lastUpdated: new Date().toISOString(),
    rank: 2,
    score: 92,
    reasons: { fitnessScore: 1.0, brandingScore: 0.5, mileageBalancing: 0.9, otherFactors: [] },
  },
  {
    id: 'TS03',
    fleetNumber: 'KM-03',
    status: 'standby',
    mileage: 150200,
    certificates: [{ dept: 'Braking', validFrom: '2022-03-01', validTo: '2024-03-01', status: 'expired' }],
    jobCards: [{ id: 'JC-123', type: 'General Overhaul', severity: 'high', status: 'open' }],
    branding: null,
    cleaningReady: true,
    bayPosition: 'B1',
    lastUpdated: new Date().toISOString(),
    rank: 3,
    score: 40,
    reasons: { fitnessScore: 0.2, brandingScore: 0.5, mileageBalancing: 0.6, otherFactors: ['Certificate expired', 'High severity job card open'] },
  },
  {
    id: 'TS04',
    fleetNumber: 'KM-04',
    status: 'IBL',
    mileage: 210000,
    certificates: [{ dept: 'Braking', validFrom: '2023-04-01', validTo: '2025-04-01', status: 'valid' }],
    jobCards: [],
    branding: { contractId: 'BR-B2', exposureHoursRequired: 300, exposureAchieved: 290 },
    cleaningReady: true,
    bayPosition: 'C1',
    lastUpdated: new Date().toISOString(),
    rank: 4,
    score: 88,
    reasons: { fitnessScore: 0.9, brandingScore: 1.0, mileageBalancing: 0.4, otherFactors: ['High mileage'] },
  },
    {
    id: 'TS05',
    fleetNumber: 'KM-05',
    status: 'service',
    mileage: 75000,
    certificates: [{ dept: 'Braking', validFrom: '2023-05-01', validTo: '2025-05-01', status: 'valid' }],
    jobCards: [],
    branding: null,
    cleaningReady: true,
    bayPosition: 'A3',
    lastUpdated: new Date().toISOString(),
    rank: 5,
    score: 98,
    reasons: { fitnessScore: 1.0, brandingScore: 0.5, mileageBalancing: 0.95, otherFactors: ['Low mileage, good condition'] },
  },
  {
    id: 'TS06',
    fleetNumber: 'KM-06',
    status: 'standby',
    mileage: 130000,
    certificates: [{ dept: 'Braking', validFrom: '2023-06-01', validTo: '2025-06-01', status: 'valid' }],
    jobCards: [{ id: 'JC-456', type: 'Door System Check', severity: 'low', status: 'open' }],
    branding: null,
    cleaningReady: false,
    bayPosition: 'B2',
    lastUpdated: new Date().toISOString(),
    rank: 6,
    score: 75,
    reasons: { fitnessScore: 0.8, brandingScore: 0.5, mileageBalancing: 0.8, otherFactors: ['Low severity job card', 'Cleaning needed'] },
  },
];
